### ISSUE TITLE
Archived/Invisible space handling

### ISSUE THREAD

**Issue by buddh4** [humhub-contrib/popover-vcard#5]
Currently there is no check for space/profile visibility. E.g. when mentioning a space.

**Comment by MasterMindNET** [comment]
Good day, @buddh4,
I am a new to the project and I would like to try to find out what's wrong with it.

Could you please specify it with a bit more details?
Some paths to a file(module) and a screenshoot woulb be great.
Thanks!

**Comment by luke-** [comment]
@MasterMindNET e.g. For private spaces (i.e. invisible space for non-members) there should also be no popover (with more information) for non-members. A case here could be if space was mentioned. (@Space Name) 

But I do not see a problem for archived spaces.

**Comment by MasterMindNET** [comment]
> @MasterMindNET e.g. For private spaces (i.e. invisible space for non-members) there should also be no popover (with more information) for non-members. A case here could be if space was mentioned. (@space Name)
> 
> But I do not see a problem for archived spaces.

If a user is not a member of this space, he or she should not see the popover, isn't it?

**Comment by luke-** [comment]
I think the cases are very rare. It should actually only occur if a user mentions a space (using @ character) and another user has no access to this private Space. In this case the popover should be disabled.

**Comment by MasterMindNET** [comment]
How about some kind of warning or popover/hint?
Like:
"This space is private, and you are not allowed to view it" | This space is private" | "Only members of this Space can view it" or similar some title/text. (for now, I will update it with just hidden popover-vcard)
Because it may lack some UX (the user may not know it and can be confused that it is not working for this one).

Does the user class has the same property (`visibility`) to detect if it can be viewed?
And where a user can change if a popover should be visible, does it exists or not (such property)?

Just let me know what you think about this point.

**Comment by luke-** [comment]
Thanks for the PR it is gemerged.


Normally there should be no links for private spaces in use, so it is no big problem if there is no VCard available in that case.  

Completely invisible user profiles are not planned. In case Guest Access is activated, it makes sense to display User VCards only if the user wants to be visible to guests. If you want you can provide a PR for this.

Thanks!
